language: android
jdk: oraclejdk8
sudo: true
env:
  global:
  - EMULATOR_API=android-23
  - EMULATOR_ABI=armeabi-v7a
branches:
  only:
  - master
android:
  components:
    # Use the latest revision of Android SDK Tools:
    - tools
install:
  - echo 'count=0' > /home/travis/.android/repositories.cfg
  - echo y | sdkmanager "platform-tools" >/dev/null
  - echo y | sdkmanager "tools" >/dev/null
  - echo y | sdkmanager "build-tools;29.0.0" >/dev/null
  - echo y | sdkmanager "platforms;android-29" >/dev/null
  - echo y | sdkmanager "extras;android;m2repository" >/dev/null
  - echo y | sdkmanager "ndk-bundle" >/dev/null
  - echo y | sdkmanager "cmake;3.10.2.4988404" >/dev/null
  - echo y | sdkmanager "lldb;3.1" >/dev/null
  - echo y | sdkmanager "platforms;${EMULATOR_API}" >/dev/null
  - echo y | sdkmanager "system-images;${EMULATOR_API};google_apis;${EMULATOR_ABI}" >/dev/null
  - echo no | avdmanager create avd -f -n test -k "system-images;${EMULATOR_API};google_apis;${EMULATOR_ABI}"

before_script:
  # Set up local.properties
  - touch local.properties
  # Export NDK HOME:
  - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
  # Start an emulator:
  - $ANDROID_HOME/emulator/emulator -verbose -avd test -qemu -no-accel -no-snapshot -no-window -camera-back none -camera-front none &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - adb logcat > logcat.log 2>&1 &
script:
  - ./gradlew testCI -PbuildAbis=$EMULATOR_ABI --console=plain
after_success:
  - ./gradlew coverageCI
after_failure:
  - cat logcat.log
